sudo: required
services:
  - docker
branches:
  except:
  - master
  - ssr
  - mingw
  - rm
addons:
  apt:
    packages:
    - make
    - git
script:
- cd docker/client && make
- cd docker/server && make
deploy:
  provider: releases
  api_key:
    secure: pOP6wenJDeL7DX+/SRYL/bfXY/bzoXfBVlbcrdWcN6oXnzAbPfSMU3coVfqnNnApf0cOBz2IZfRu2zIG4SlqkPfD+uXRIeK8xMQ9gVmuV+Am2j8heIJlSDekoj7k25elCLD6ojA0X4d37KFlmT4Hsep3O9AxhGJ5S2rEDRjEG/Y8FS8qjLcJn+QEvc0bri4cW928yDjGvuOqAH+0PKF3zLxXaayJVUFN6scF7ip15tSEuMzXYgpUuBqYVTQkQduG8M5ucONafZ/ryRPoiwLLlCdsfzfZooCqzz5KlFmEbXKyZuTbmqNeydAT6m455H8id+KrkaFWI1MzPGT63KofMPBKDi6rlzpiIWKHpZ8OHYAjCUHfYvJ5QuaJFnMpbKIPZvEYMFUs5hnTZq7c/6DztEP6Y2hJf8sQ5ZdOXzL9ZVpJY/FrXap0i0gndlXETa40JskIYMphpNpXBqeAEZATs6GWgUXl5J49PiNOJdvszrdJaToCV8Up6h6WfK3LFYl1Ja5E9tHOszWoa1yodmUY9WqPfNXZZTCpypIHVG6dEJ6Mv/25NZVJrPYi+xE30pYXJr8EIUs6oGT5HQg1tGgP/6Ou7lCd+4lPJbf10b39FPchOJmrhgoZoLkfzDGjrYV8kY069f6XwY2OQZgD+HW5uveOBfTY8aWSZ6cAypQqE/w=
  file_glob: true
  file:
  - docker/client/ssr-client.tar.gz
  - docker/server/ssr-server.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: linusyang92/shadowsocks-libev
    tags: true
